---
- name: dump databases
  hosts: all
  vars:
  become: true
  tasks:
    - name: Backup mysql databases
      mysql_db: 
        state: dump 
        name: all 
        target: "{{ Backup_path }}/mysql-{{ db_name }}.sql"
            
    - name: Postgres
      shell:
        cmd: pg_dumpall > {{ Backup_path }}/postgres-{{ db_name }}.dump.gz
        creates: "{{ Backup_path }}/postgres-{{ db_name }}.dump.gz"
      become: yes
      become_user: postgres
